<?php
    include_once  'template/m_header.php';
?>

<div class="w3-container" style="margin-top:75px">
    <hr>
    <div class="w3-row">
        <div class="w3-col s3"></div>
        <div class="w3-col">
            <table style="font-family:Calibri;" align="center" width="100%">
                <tr style="background-color:#467898; color:white;">
                    <th class="shipmentTB3">Report Month</th>
                    <th class="shipmentTB3">Report No</th>
                    <th class="shipmentTB3">Generated Date</th>
                    <th class="shipmentTB3">Generated By</th>
                </tr>
                <?php
                for($i=0;$i<sizeof($com_id);$i++){
                    if(($i%2)==0) $color='#EEEEEE'; else $color='#F9F9F9';
                    print '<tr bgcolor="'.$color.'">
                            <td class="shipmentTB3" align="center">'.$com_month[$i].'</td>
                            <td class="shipmentTB3" align="center"><a href="index.php?components='.$components.'&action=salesman_commission_one&id='.$com_id[$i].'" style="text-decoration:none">'.str_pad($com_id[$i], 7, "0", STR_PAD_LEFT).'</a></td>
                            <td class="shipmentTB3" align="center">'.$com_gen_date[$i].'</td>
                            <td class="shipmentTB3">'.ucfirst($com_gen_by[$i]).'</td>
                        </tr>';
                }
                ?>
            </table>
        </div>
    </div>
</div>

<hr>
<br />

<?php
    include_once  'template/m_footer.php';
?>